
[databasetype]
  type = "Postgresql"

[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db"

[language]
  local = "zh-cn"

[mail]
  host = "smtp.163.com"
  pass = ""
  port = 465
  to = ""
  user = ""

[mysql]

  [mysql.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [mysql.read]
    addr = "127.0.0.1:5432"
    name = "go_gin_api"
    pass = "123456"
    user = "postgres"

  [mysql.write]
    addr = "127.0.0.1:5432"
    name = "go_gin_api"
    pass = "123456"
    user = "postgres"

[pgsql]

  [pgsql.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [pgsql.read]
    addr = "127.0.0.1"
    name = "go_gin_api"
    pass = "123456"
    port = "5432"
    user = "postgres"

  [pgsql.write]
    addr = "127.0.0.1"
    name = "go_gin_api"
    pass = "123456"
    port = "5432"
    user = "postgres"

[redis]
  addr = "127.0.0.1:6379"
  db = "0"
  maxretries = 3
  minidleconns = 5
  pass = ""
  poolsize = 10
